name: CI

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build_mhcapstone:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'mhcapstonegithubactions' }}
      run: |
        cd ./mhcapstone
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $mhcapstonegithubactions
        heroku container:release web -a $mhcapstonegithubactions
